### ISSUE TITLE
[Borrow] Cannot fully repay ETH loan

### ISSUE THREAD

**Issue by vasdeference** [UnFederalReserve/community#42]
**Describe the bug**

**To Reproduce**
1. Go to My Borrowings
2. Click on ETH (outstanding loan)
3. Click Repay
4. Click Max
5. Repay Loan
6. Pay Gas / confirm in Metamask
7. Transaction confirmed
8. ETH still showing as outstanding with $0.00 and 0.0% of "borrow percentage"
9. Click on ETH
10. Click MAX
11. showing 0.00000000013 ETH
12. Repay
13. Pay Gas /confirm
14. Transaction
15. Still show ETH as outstanding.

**Expected behavior**
Be able to fully repay ETH loan when choosing "Max" option

**Screenshots**
![image](https://user-images.githubusercontent.com/83833028/117483083-1d44f100-af1a-11eb-88f0-bbcd4fce25c4.png)
![image](https://user-images.githubusercontent.com/83833028/117483116-27ff8600-af1a-11eb-9e43-72446337176b.png)

**Desktop (please complete the following information):**
 - Mac OS Mojave 10.14.6
 - Google Chrome
 - Version 90.0.4430.93 (Official Build) (x86_64)

**Wallet Version (please complete the following information):**
 - Wallet
 - Public Address: 0x0010114u1212u1241

**Additional context**

**Comment by Jarsir** [comment]
I have this same issue repaying my loan. I repaid it 4 times to try to get rid of the dust and now I am left with dust of 4e-18 eth which is so small of an amount that the decimals for the platform don't support it. because of this tiny loan most of my eth is locked on the platform, I have no other loans. It should be locking up the 80% ratio between borrowing and lending which would be such a small amount I would just abandon it, but it is not, and now i have paid an extra $800 in gas fees to try to get off platform.

**Comment by hskainth** [comment]
`Interest earned/accrued is automatically compounded per block. Completing any transaction (including withdrawal/repayment) requires a certain amount of blocks. While the transaction is being completed, new interest is going to be computed over the course of this operation. In the case of ETH, this is the fraction of the smallest decimal thus so-called “dust” is created.
ETH “dust” presents itself only with ETH supply/borrow and is prevalent across other Defi platforms.`
